### ISSUE TITLE
panic: Could not resolve symbol: main

### ISSUE THREAD

**Issue by nikpivkin** [pherrymason/c3-lsp#44]
If you enter a dot after `main`, the server lsp crashes.
```c
import std::io;

fn int main() {
    io::printn("main.");
    return 0;
}
```

Trace:
```bash
Info  - 18:27:16] Connection to server got closed. Server will restart.
true
2024/08/15 18:27:16.638  DEBUG [C3-LSP.parser] No crash reports
2024/08/15 18:27:16.645   NOTE [C3-LSP] reading from stdin, writing to stdout
2024/08/15 18:27:16.645   INFO [C3-LSP] new stream connection
2024/08/15 18:27:16.646  DEBUG [C3-LSP:rpc] jsonrpc2: --> request #0: initialize: {"capabilities":{"general":{"markdown":{"parser":"marked","version":"1.1.0"},"positionEncodings":["utf-16"],"regularExpressions":{"engine":"ECMAScript","version":"ES2020"},"staleRequestSupport":{"cancel":true,"retryOnContentModified":["textDocument/semanticTokens/full","textDocument/semanticTokens/range","textDocument/semanticTokens/full/delta"]}},"notebookDocument":{"synchronization":{"dynamicRegistration":true,"executionSummarySupport":true}},"textDocument":{"callHierarchy":{"dynamicRegistration":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"disabledSupport":true,"dynamicRegistration":true,"honorsChangeAnnotations":true,"isPreferredSupport":true,"resolveSupport":{"properties":["edit"]}},"codeLens":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"completion":{"completionItem":{"commitCharactersSupport":true,"deprecatedSupport":true,"documentationFormat":["markdown","plaintext"],"insertReplaceSupport":true,"insertTextModeSupport":{"valueSet":[1,2]},"labelDetailsSupport":true,"preselectSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"completionList":{"itemDefaults":["commitCharacters","editRange","insertTextFormat","insertTextMode","data"]},"contextSupport":true,"dynamicRegistration":true,"insertTextMode":2},"declaration":{"dynamicRegistration":true,"linkSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"diagnostic":{"dynamicRegistration":true,"relatedDocumentSupport":false},"documentHighlight":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"documentSymbol":{"dynamicRegistration":true,"hierarchicalDocumentSymbolSupport":true,"labelSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"foldingRange":{"dynamicRegistration":true,"foldingRange":{"collapsedText":false},"foldingRangeKind":{"valueSet":["comment","imports","region"]},"lineFoldingOnly":true,"rangeLimit":5000},"formatting":{"dynamicRegistration":true},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"inlayHint":{"dynamicRegistration":true,"resolveSupport":{"properties":["tooltip","textEdits","label.tooltip","label.location","label.command"]}},"inlineValue":{"dynamicRegistration":true},"linkedEditingRange":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"publishDiagnostics":{"codeDescriptionSupport":true,"dataSupport":true,"relatedInformation":true,"tagSupport":{"valueSet":[1,2]},"versionSupport":false},"rangeFormatting":{"dynamicRegistration":true,"rangesSupport":true},"references":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"honorsChangeAnnotations":true,"prepareSupport":true,"prepareSupportDefaultBehavior":1},"selectionRange":{"dynamicRegistration":true},"semanticTokens":{"augmentsSyntaxTokens":true,"dynamicRegistration":true,"formats":["relative"],"multilineTokenSupport":false,"overlappingTokenSupport":false,"requests":{"full":{"delta":true},"range":true},"serverCancelSupport":true,"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"],"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator","decorator"]},"signatureHelp":{"contextSupport":true,"dynamicRegistration":true,"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true,"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"typeHierarchy":{"dynamicRegistration":true}},"window":{"showDocument":{"support":true},"showMessage":{"messageActionItem":{"additionalPropertiesSupport":true}},"workDoneProgress":true},"workspace":{"applyEdit":true,"codeLens":{"refreshSupport":true},"configuration":true,"diagnostics":{"refreshSupport":true},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true,"relativePatternSupport":true},"executeCommand":{"dynamicRegistration":true},"fileOperations":{"didCreate":true,"didDelete":true,"didRename":true,"dynamicRegistration":true,"willCreate":true,"willDelete":true,"willRename":true},"foldingRange":{"refreshSupport":true},"inlayHint":{"refreshSupport":true},"inlineValue":{"refreshSupport":true},"semanticTokens":{"refreshSupport":true},"symbol":{"dynamicRegistration":true,"resolveSupport":{"properties":["location.range"]},"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"workspaceEdit":{"changeAnnotationSupport":{"groupsOnLabel":true},"documentChanges":true,"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"Visual Studio Code","version":"1.92.1"},"locale":"en","processId":8244,"rootPath":"/Users/nikita/projects/c3c-test","rootUri":"file:///Users/nikita/projects/c3c-test","trace":"off","workspaceFolders":[{"name":"c3c-test","uri":"file:///Users/nikita/projects/c3c-test"}]}
2024/08/15 18:27:16.651  DEBUG [C3-LSP:rpc] jsonrpc2: <-- result #0: initialize: {"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":true},"completionProvider":{"triggerCharacters":[".",":"]},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","],"retriggerCharacters":[")"]},"declarationProvider":true,"definitionProvider":true,"renameProvider":true,"workspace":{"fileOperations":{"didRename":{"filters":[{"pattern":{"glob":"**/*.{c3,c3i}"}}]},"didDelete":{"filters":[{"pattern":{"glob":"**/*.{c3,c3i}"}}]}}}},"serverInfo":{"name":"C3-LSP","version":"0.0.9"}}
2024/08/15 18:27:16.651  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: initialized: {}
2024/08/15 18:27:16.652  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: textDocument/didOpen: {"textDocument":{"languageId":"c3","text":"import std::io;\n\nfn int main() {\n    io::printn(\"main.\");\n    return 0;\n}","uri":"file:///Users/nikita/projects/c3c-test/main.c3","version":19}}
2024/08/15 18:27:16.656  DEBUG [C3-LSP:rpc] jsonrpc2: --> request #1: textDocument/completion: {"context":{"triggerKind":1},"position":{"character":21,"line":3},"textDocument":{"uri":"file:///Users/nikita/projects/c3c-test/main.c3"}}
2024/08/15 18:27:16.656  DEBUG [C3-LSP.parser] building completion list: "."
panic: Could not resolve symbol: main

goroutine 11 [running]:
github.com/pherrymason/c3-lsp/internal/lsp/search.(*Search).resolve(0x140000f3960, {0x103d06978, 0x140007a2c00}, {0x14000201020, 0x27}, {0x14000201080, 0x1f}, 0x1400019e7e0, {0x140008422f0?, 0x0?, ...}, ...)
	github.com/pherrymason/c3-lsp/internal/lsp/search/find_parent.go:225 +0x83c
github.com/pherrymason/c3-lsp/internal/lsp/search.(*Search).findInParentSymbols(_, {{{0x14000030d01, 0x4}, {{0x3, 0x10}, {0x3, 0x14}}, {0x0, 0x0, 0x0}, ...}, ...}, ...)
	github.com/pherrymason/c3-lsp/internal/lsp/search/find_parent.go:43 +0xc9c
github.com/pherrymason/c3-lsp/internal/lsp/search.(*Search).findParentType(_, {{{0x14000030d01, 0x4}, {{0x3, 0x10}, {0x3, 0x14}}, {0x0, 0x0, 0x0}, ...}, ...}, ...)
	github.com/pherrymason/c3-lsp/internal/lsp/search/search_completion_list.go:317 +0x54
github.com/pherrymason/c3-lsp/internal/lsp/search.(*Search).BuildCompletionList(0x140000f3960, {0x140002011a0?, 0x1400027ac01?}, {0x89?, 0x14000249908?}, 0x1400019e7e0)
	github.com/pherrymason/c3-lsp/internal/lsp/search/search_completion_list.go:194 +0x58c
github.com/pherrymason/c3-lsp/internal/lsp/handlers.(*Handlers).TextDocumentCompletion(0x140000f3950, 0x140007b2028?, 0x1400027ac90)
	github.com/pherrymason/c3-lsp/internal/lsp/handlers/TextDocumentCompletion.go:13 +0x6c
github.com/tliron/glsp/protocol_3_16.(*Handler).Handle(0x140000de600, 0x14000202e10)
	github.com/tliron/glsp@v0.2.3-0.20240511204206-c63625272e79/protocol_3_16/handler.go:372 +0x15c0
github.com/tliron/glsp/server.(*Server).handle(0x1400007e780, {0x103d04660, 0x1400019e070}, 0x140001821b0, 0x140001109c0)
	github.com/tliron/glsp@v0.2.3-0.20240511204206-c63625272e79/server/handler.go:47 +0x248
github.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0x140000ef2e0, {0x103d04660, 0x1400019e070}, 0x140001821b0, 0x140001109c0)
	github.com/sourcegraph/jsonrpc2@v0.2.0/handler_with_error.go:21 +0x4c
github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0x140001821b0, {0x103d04660, 0x1400019e070})
	github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:205 +0x2a4
created by github.com/sourcegraph/jsonrpc2.NewConn in goroutine 1
	github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:62 +0x1d0
[Error - 18:27:16] The C3LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 18:27:16] Server process exited with code 2.
```

**Comment by pherrymason** [comment]
Mm, it shouldn't try to find autocomplete inside a literal. Let me work on a fix.

**Comment by pherrymason** [comment]
Thank you for your report, very detailed.

I've fixed this issue and placed the seed to further improve the information about what's currently under cursor.

**Comment by nikpivkin** [comment]
Thank you for your work!
