### ISSUE TITLE
Hovering on struct method causes infintie loop

### ISSUE THREAD

**Issue by pherrymason** [pherrymason/c3-lsp#7]
**Describe the bug**
Searching for symbol declaration (caused by a hover on symbol) crashes the server as it enters into an infinite loop.

**To Reproduce**
1. With code like this:
```
fn void System.init(System* system) {
}
```
2. Hover on `init`
3. Server crashes

**Expected behavior**
Should not crash, maybe even return null to client as we are hovering on the very same declaration.

**Log**
```
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module std::io
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module std::time
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module std::time::clock
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module std::thread
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module cpu
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside cpu file /path/src/cpu.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/cpu.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module cpu

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module inst
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside inst file /path/src/inst.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/inst.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module inst

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module debug
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside debug file /path/src/debugger/debug.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/debugger/debug.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module debug

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module raylib
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module libc
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module io
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside io file /path/src/io.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/io.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module io

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module ppu
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside ppu file /path/src/ppu.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/ppu.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module ppu

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module lcd
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside lcd file /path/src/lcd.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/lcd.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module lcd

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module raylib
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module input
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside input file /path/src/input.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/input.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module input

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module raylib
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module serial
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside serial file /path/src/serial.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/serial.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module serial

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module apu
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside apu file /path/src/apu.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/apu.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module apu

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/audio/sweep.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module apu::sweep

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module types
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside types file /path/src/types.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/types.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module types

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/audio/square.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module apu::square

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module apu::lengthduty
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside apu::lengthduty file /path/src/audio/lengthduty.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/audio/lengthduty.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module apu::lengthduty

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/apu.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module apu

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module std::io
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module std::thread
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module types
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside types file /path/src/types.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/types.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module types

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module system
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside system file /path/src/system.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/system.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module system

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module std::time
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module std::time::clock
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module cpu
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside cpu file /path/src/cpu.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/cpu.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module cpu

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module inst
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside inst file /path/src/inst.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/inst.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module inst

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module debug
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside debug file /path/src/debugger/debug.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/debugger/debug.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module debug

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module raylib
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module libc
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module io
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside io file /path/src/io.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/io.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module io

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module ppu
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside ppu file /path/src/ppu.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/ppu.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module ppu

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module lcd
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside lcd file /path/src/lcd.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/lcd.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module lcd

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module raylib
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module input
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside input file /path/src/input.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/input.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module input

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module raylib
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module cart
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside cart file /path/src/cart.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/cart.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module cart

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module mappers
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside mappers file /path/src/mappers/mapper.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/mappers/mapper.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module mappers

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/mappers/mcb3.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module mappers::mcb3

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module types
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside types file /path/src/types.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/types.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module types

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module cart
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside cart file /path/src/cart.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/cart.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module cart

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module system
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside system file /path/src/system.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/system.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module system

2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module std::io
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module std::time
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module std::time::clock
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module std::thread
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module cpu
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside cpu file /path/src/cpu.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/cpu.c3
2024/05/04 19:01:17.925 DEBUG [C3-LSP.parser] Checking module cpu

2024/05/04 19:01:17.926 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration: search in imported module inst
2024/05/04 19:01:17.926 DEBUG [C3-LSP.parser] _findSymbolDeclarationInModule: search with fdcdd inside inst file /path/src/inst.c3
2024/05/04 19:01:17.926 DEBUG [C3-LSP.parser] findClosestSymbolDeclaration on doc /path/src/inst.c3
2024/05/04 19:01:17.926 DEBUG [C3-LSP.parser] Checking module inst

```

Stack
```
runtime stack:
runtime.throw({0x10494a69c?, 0x104793ae4?})
	/usr/local/go/src/runtime/panic.go:1077 +0x40 fp=0x16b69aac0 sp=0x16b69aa90 pc=0x10479b570
runtime.newstack()
	/usr/local/go/src/runtime/stack.go:1107 +0x458 fp=0x16b69ac70 sp=0x16b69aac0 pc=0x1047b57d8
traceback: unexpected SPWRITE function runtime.morestack
runtime.morestack()
	/usr/local/go/src/runtime/asm_arm64.s:316 +0x70 fp=0x16b69ac70 sp=0x16b69ac70 pc=0x1047cb8e0

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x12cfa22?, 0x11d4e87?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x1400004bf50 sp=0x1400004bf30 pc=0x10479e2c8
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x104c5c820)
	/usr/local/go/src/runtime/mgcscavenge.go:425 +0x5c fp=0x1400004bf80 sp=0x1400004bf50 pc=0x10478873c
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:658 +0xac fp=0x1400004bfb0 sp=0x1400004bf80 pc=0x104788cfc
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:201 +0x28 fp=0x1400004bfd0 sp=0x1400004bfb0 pc=0x10477fbb8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400004bfd0 sp=0x1400004bfd0 pc=0x1047cddd4
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:201 +0xac

...

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x54cebd4ab9f73?, 0x3?, 0xdc?, 0x5?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x14000325f30 sp=0x14000325f10 pc=0x10479e2c8
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1295 +0xd8 fp=0x14000325fd0 sp=0x14000325f30 pc=0x1047815e8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000325fd0 sp=0x14000325fd0 pc=0x1047cddd4
created by runtime.gcBgMarkStartWorkers in goroutine 21
	/usr/local/go/src/runtime/mgc.go:1219 +0x28
[Info  - 19:01:19] Connection to server got closed. Server will restart.
true
[Error - 19:01:19] Server process exited with code 2.
2024/05/04 19:01:19.739  INFO [C3-LSP.server] reading from stdin, writing to stdout
```

**Comment by pherrymason** [comment]
Problem comes from `findInParentSymbols`, where we are not registering which modules we already checked.
