### ISSUE TITLE
panic when entering the scope resolution operator

### ISSUE THREAD

**Issue by nikpivkin** [pherrymason/c3-lsp#76]
**Describe the bug**
```bash
2024/09/17 23:24:00 An error: exit status 1
2024/09/17 23:24:00.217  DEBUG [C3-LSP:rpc] jsonrpc2: <-- result #0: initialize: {"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":true},"completionProvider":{"triggerCharacters":[".",":"]},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","],"retriggerCharacters":[")"]},"declarationProvider":true,"definitionProvider":true,"renameProvider":true,"workspace":{"fileOperations":{"didRename":{"filters":[{"pattern":{"glob":"**/*.{c3,c3i}"}}]},"didDelete":{"filters":[{"pattern":{"glob":"**/*.{c3,c3i}"}}]}}}},"serverInfo":{"name":"C3-LSP","version":"0.3.2"}}
2024/09/17 23:24:00.217  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: initialized: {}
2024/09/17 23:24:00.218  DEBUG [C3-LSP:rpc] jsonrpc2: --> notif: textDocument/didOpen: {"textDocument":{"languageId":"c3","text":"std::","uri":"file:///Users/nikita/projects/c3-pets/main.c3","version":75}}
2024/09/17 23:24:00.220  DEBUG [C3-LSP:rpc] jsonrpc2: --> request #1: textDocument/completion: {"context":{"triggerKind":1},"position":{"character":5,"line":0},"textDocument":{"uri":"file:///Users/nikita/projects/c3-pets/main.c3"}}
2024/09/17 23:24:00.220  DEBUG [C3-LSP.parser] building completion list: ":"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x50 pc=0x102ff18a0]

goroutine 13 [running]:
github.com/pherrymason/c3-lsp/internal/lsp/search.(*Search).findSymbolsInScope(0x1400089ca58, {{0x1400094db60, 0x26}, {{{0x14000a234d0, 0x1, 0x1}}, 0x1}, {{0x0, 0x5}, 0x1}}, ...)
	github.com/pherrymason/c3-lsp/internal/lsp/search/search_find_symbols_scope.go:42 +0x250
github.com/pherrymason/c3-lsp/internal/lsp/search.(*Search).BuildCompletionList(0x1400089ca58, {{0x0, 0x5}, {0x1400094dc50, 0x26}, 0x0, 0x0, 0x0}, 0x1400012ee80)
	github.com/pherrymason/c3-lsp/internal/lsp/search/search_completion_list.go:288 +0x600
github.com/pherrymason/c3-lsp/internal/lsp/server.(*Server).TextDocumentCompletion(0x1400089c9a0, 0x14000a4e1d8?, 0x14000a4c3f0)
	github.com/pherrymason/c3-lsp/internal/lsp/server/TextDocumentCompletion.go:20 +0xe8
github.com/tliron/glsp/protocol_3_16.(*Handler).Handle(0x14000142600, 0x14000955630)
	github.com/tliron/glsp@v0.2.3-0.20240511204206-c63625272e79/protocol_3_16/handler.go:372 +0x15c0
github.com/tliron/glsp/server.(*Server).handle(0x1400007a840, {0x104f1e140, 0x1400017c000}, 0x14000108120, 0x14000200d80)
	github.com/tliron/glsp@v0.2.3-0.20240511204206-c63625272e79/server/handler.go:47 +0x248
github.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0x14000997980, {0x104f1e140, 0x1400017c000}, 0x14000108120, 0x14000200d80)
	github.com/sourcegraph/jsonrpc2@v0.2.0/handler_with_error.go:21 +0x4c
github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0x14000108120, {0x104f1e140, 0x1400017c000})
	github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:205 +0x2a4
created by github.com/sourcegraph/jsonrpc2.NewConn in goroutine 1
	github.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:62 +0x1d0
[Error - 23:24:00] The C3LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 23:24:00] Server process exited with code 2.
```
Code:
```c
std::
```
**Desktop (please complete the following information):**
 - OS: MacOS ARM
 - Editor: VS Code
 - Version: v0.3.2

**Comment by Caleb-o** [comment]
I just got this issue too, trying to do an import. Tried on both 0.3.2 and following the latest commit [f7add67](https://github.com/pherrymason/c3-lsp/commit/f7add67f459e568b97a613f010664f1696d8b476)

**Comment by pherrymason** [comment]
I cannot reproduce it.
Could you send me a project that reproduces this?
It would also help if you describe me the file and line where it breaks when you write `std::`

**Comment by nikpivkin** [comment]
@pherrymason  
1. panic occurs after the second colon is entered `std:` -> `std::`. 
2.
```bash
> ls
main.c
```

**Comment by pherrymason** [comment]
@nikpivkin does main.c contains any other text? Or is it empty before the adding of `std::`?

**Comment by nikpivkin** [comment]
empty, just import
```bash
> cat main.c3
import std:%
```

**Comment by pherrymason** [comment]
Does it still fail with last version in `main`?

**Comment by pherrymason** [comment]
Does it still fail with last version in main @nikpivkin ?

**Comment by nikpivkin** [comment]
No, there's still a problem. A check needs to be done [here](https://github.com/pherrymason/c3-lsp/blob/main/server/internal/lsp/search/search_find_symbols_scope.go#L42), as `currentModule` can be nil.

**Comment by pherrymason** [comment]
Sorry, I noticed I still did not push. Will ping you again when I can.

> A check needs to be done [here](https://github.com/pherrymason/c3-lsp/blob/main/server/internal/lsp/search/search_find_symbols_scope.go#L42), as currentModule can be nil.

Yes! that's the change I did precisely

**Comment by pherrymason** [comment]
Just pushed the change @nikpivkin
