### ISSUE TITLE
helix editor integration 

### ISSUE THREAD

**Issue by Dev-loper0** [pherrymason/c3-lsp#87]
**Describe the bug**
invalid memory address or nil pointer dereference.

**To Reproduce**
1. install helix
2. add new language server "c3 lsp" 
3. run the editor 
4. go to logs generated by helix

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop os
 - Editor : Helix

**logs**
2024-11-27T22:44:08.110 helix_lsp::transport [ERROR] c3-lsp err: <- StreamClosed
2024-11-27T22:48:55.341 helix_lsp::transport [ERROR] c3-lsp err <- "2024/11/27 22:48:55.341  DEBUG [C3-LSP.parser] No crash reports\n"
2024-11-27T22:48:55.360 helix_lsp::transport [ERROR] c3-lsp err <- "2024/11/27 22:48:55.360   NOTE [C3-LSP] reading from stdin, writing to stdout\n"
2024-11-27T22:48:55.360 helix_lsp::transport [ERROR] c3-lsp err <- "2024/11/27 22:48:55.360   INFO [C3-LSP] new stream connection\n"
2024-11-27T22:48:55.361 helix_lsp::transport [ERROR] c3-lsp err <- "2024/11/27 22:48:55.361  DEBUG [C3-LSP:rpc] jsonrpc2: --> request #0: initialize: {\"capabilities\":{\"general\":{\"positionEncodings\":[\"utf-8\",\"utf-32\",\"utf-16\"]},\"textDocument\":{\"codeAction\":{\"codeActionLiteralSupport\":{\"codeActionKind\":{\"valueSet\":[\"\",\"quickfix\",\"refactor\",\"refactor.extract\",\"refactor.inline\",\"refactor.rewrite\",\"source\",\"source.organizeImports\"]}},\"dataSupport\":true,\"disabledSupport\":true,\"isPreferredSupport\":true,\"resolveSupport\":{\"properties\":[\"edit\",\"command\"]}},\"completion\":{\"completionItem\":{\"deprecatedSupport\":true,\"insertReplaceSupport\":true,\"resolveSupport\":{\"properties\":[\"documentation\",\"detail\",\"additionalTextEdits\"]},\"snippetSupport\":true,\"tagSupport\":{\"valueSet\":[1]}},\"completionItemKind\":{}},\"hover\":{\"contentFormat\":[\"markdown\"]},\"inlayHint\":{\"dynamicRegistration\":false},\"publishDiagnostics\":{\"tagSupport\":{\"valueSet\":[1,2]},\"versionSupport\":true},\"rename\":{\"dynamicRegistration\":false,\"honorsChangeAnnotations\":false,\"prepareSupport\":true},\"signatureHelp\":{\"signatureInformation\":{\"activeParameterSupport\":true,\"documentationFormat\":[\"markdown\"],\"parameterInformation\":{\"labelOffsetSupport\":true}}}},\"window\":{\"workDoneProgress\":true},\"workspace\":{\"applyEdit\":true,\"configuration\":true,\"didChangeConfiguration\":{\"dynamicRegistration\":false},\"didChangeWatchedFiles\":{\"dynamicRegistration\":true,\"relativePatternSupport\":false},\"executeCommand\":{\"dynamicRegistration\":false},\"fileOperations\":{\"didRename\":true,\"willRename\":true},\"inlayHint\":{\"refreshSupport\":false},\"symbol\":{\"dynamicRegistration\":false},\"workspaceEdit\":{\"documentChanges\":true,\"failureHandling\":\"abort\",\"normalizesLineEndings\":false,\"resourceOperations\":[\"create\",\"rename\",\"delete\"]},\"workspaceFolders\":true}},\"clientInfo\":{\"name\":\"helix\",\"version\":\"24.3 (2cadec0b)\"},\"processId\":435810,\"rootPath\":\"/home/fritz0x0/Desktop\",\"rootUri\":null,\"workspaceFolders\":[]}\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "panic: runtime error: invalid memory address or nil pointer dereference\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc3917b]\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "goroutine 5 [running]:\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "github.com/pherrymason/c3-lsp/internal/lsp/server.(*Server).Initialize(_, {_, _}, {_, _}, {{0xd3ab40, 0xc0009929f0}, 0xc000948c80, {0xcd9e00, 0x14339c8}, ...}, ...)\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "\tgithub.com/pherrymason/c3-lsp/internal/lsp/server/Initialize.go:60 +0x4db\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "github.com/pherrymason/c3-lsp/internal/lsp/server.NewServer.func2(0xc000941040, 0xc000122510)\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "\tgithub.com/pherrymason/c3-lsp/internal/lsp/server/server.go:113 +0x105\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "github.com/tliron/glsp/protocol_3_16.(*Handler).Handle(0xc00010a600, 0xc000941040)\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "\tgithub.com/tliron/glsp@v0.2.3-0.20240511204206-c63625272e79/protocol_3_16/handler.go:126 +0x325\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "github.com/tliron/glsp/server.(*Server).handle(0xc0000be780, {0x1000c80, 0xc000148000}, 0xc000122000, 0xc0001803c0)\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "\tgithub.com/tliron/glsp@v0.2.3-0.20240511204206-c63625272e79/server/handler.go:47 +0x28c\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "github.com/sourcegraph/jsonrpc2.(*HandlerWithErrorConfigurer).Handle(0xc000946690, {0x1000c80, 0xc000148000}, 0xc000122000, 0xc0001803c0)\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "\tgithub.com/sourcegraph/jsonrpc2@v0.2.0/handler_with_error.go:21 +0x57\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc000122000, {0x1000c80, 0xc000148000})\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "\tgithub.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:205 +0x2dd\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "created by github.com/sourcegraph/jsonrpc2.NewConn in goroutine 1\n"
2024-11-27T22:48:55.364 helix_lsp::transport [ERROR] c3-lsp err <- "\tgithub.com/sourcegraph/jsonrpc2@v0.2.0/conn.go:62 +0x1e6\n"
2024-11-27T22:48:55.366 helix_lsp::transport [ERROR] c3-lsp err: <- StreamClosed
2024-11-27T22:48:55.366 helix_lsp [ERROR] failed to initialize language server: server closed the stream

**Comment by sudokit** [comment]
+1 happens here too

**Comment by pherrymason** [comment]
Could you try this https://github.com/pherrymason/c3-lsp/actions/runs/12147202612/artifacts/2269628742 and see if it fixes this issue? (It's a zip with linux, mac and windows builds)

**Comment by sudokit** [comment]
And this seems to also fix this issue for me, atleast.
